function d=mydialog(Name,on)
    d = dialog('units','normalized','Position',[1/2-1/5,1/2-1/10,1/2.5,1/5],'Name','interative');

    txt = uicontrol('Parent',d,...
               'Style','text',...
               'units','normalized',...
               'Position',[1/10,1/5,8/10,2/5],...
               'String',Name);
   if(on==1)
    btn = uicontrol('Parent',d,...
                'units','normalized',...
               'Position',[2/5,1/5,1/5,1/5],...
               'String','OK',...
               'Callback','delete(gcf)');
   end
end